=== kroim/MISP/app/files/warninglists/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-warninglists",
  "id": "https://www.github.com/MISP/misp-warninglists/schema.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "list": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "type": {
      "type": "string",
      "enum": [
        "string",
        "substring",
        "hostname",
        "cidr"
      ]
    },
    "matching_attributes": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "list",
    "description",
    "version",
    "name",
    "type"
  ]
}

=== kroim/MISP/app/files/warninglists/lists/automated-malware-analysis/list.json
{
  "name": "List of known domains used by automated malware analysis services & security vendors",
  "version": 3,
  "description": "Domains used by automated malware analysis services & security vendors",
  "type": "substring",
  "matching_attributes": [
    "domain",
    "hostname",
    "domain|ip",
    "url"
  ],
  "list": [
    "virustotal.com",
    "malwr.com",
    "hybrid-analysis.com",
    "emergingthreats.net",
    "joesandbox.com",
    "anlyz.io",
    "detux.org",
    "akana.mobiseclab.org",
    "sandbox.pikker.ee",
    "www.threatexpert.com",
    "www.vicheck.ca",
    "reverse.it",
    "mcafee.com",
    "symantec.com",
    "securelist.com",
    "carbonblack.com",
    "app.any.run"
  ]
}

=== kroim/MISP/app/files/warninglists/lists/microsoft/list.json
{
  "name": "List of known microsoft domains",
  "version": 2,
  "description": "Event contains one or more entries of known microsoft domains",
  "matching_attributes": [
    "domain",
    "hostname",
    "domain|ip"
  ],
  "type": "hostname",
  "list": [
    ".files-df.1drv.com",
    ".files.1drv.com",
    ".aadrm.com",
    ".afx.ms",
    ".akadns.net",
    ".aspnetcdn.com",
    ".azure-int.net",
    ".azure-mobile.net",
    ".azure.com",
    ".cloudapp.azure.com",
    "azure.com",
    ".azure.net",
    ".cloudapp.azure.net",
    ".azureedge.net",
    ".azurewebsites.net",
    ".bing-exp.com",
    ".bing-int.com",
    ".bing.com",
    "bing.com",
    "download.cortana.cn.bing.com",
    ".bing.net",
    ".ceipmsn.com",
    ".cloudapp.net",
    ".codeplex.com",
    ".discoverbing.com",
    ".getmicrosoftkey.com",
    ".gfx-int.ms",
    "gfx-int.ms",
    ".gfx.ms",
    ".healthvault-ppe.co.uk",
    ".healthvault-ppe.com",
    "healthvault-ppe.com",
    ".healthvault.co.uk",
    ".healthvault.com",
    ".hotmail-int.com",
    "hotmail.co.uk",
    ".hotmail.com",
    "hotmail.com",
    "iespdytst",
    "ieta-wa-24",
    ".live-int.com",
    ".live-int.net",
    ".live-partner.com",
    ".live-ppe.net",
    ".live.com",
    ".live.fi",
    "live.fi",
    ".live.net",
    ".livefilestore-int.com",
    ".livefilestore.com",
    ".livemeeting.com",
    ".lync.com",
    ".mesh.com",
    ".mgmt.live",
    ".microsoft-int.com",
    ".microsoft.com",
    ".redmond.corp.microsoft.com",
    "download.microsoft.com",
    "iespdytst.redmond.corp.microsoft.com",
    "microsoft.com",
    "powerusers-staging.microsoft.com",
    "powerusers.microsoft.com",
    "telecommand.telemetry.microsoft.com",
    "vortex-sandbox.data.microsoft.com",
    "watson.telemetry.microsoft.com",
    ".microsoft.com.au",
    ".microsoft.com.tr",
    ".microsoft.fr",
    ".microsoftonline-int.com",
    ".microsoftonline-p-int.com",
    ".microsoftonline-p.com",
    ".microsoftonline-p.net",
    ".microsoftonline.com",
    ".microsoftonline.net",
    ".microsoftprime.com",
    ".microsoftstore.com",
    "za.microsoftstore.com",
    ".microsoftstore.com.br",
    ".microsoftstore.com.cn",
    ".microsoftstore.com.hk",
    ".microsofttranslator.com",
    ".microsoftvirtualacademy.com",
    ".modern.ie",
    "modern.ie",
    ".msads.net",
    ".vo.msecnd.net",
    ".msgamestudios.com",
    ".msn-int.com",
    ".msn.cn",
    ".msn.co.jp",
    ".msn.com",
    ".msn.com.cn",
    ".msocdn.com",
    ".firstpartyapps.oaspapps.com",
    ".office-int.com",
    "office-int.com",
    ".office-int.net",
    ".office.com",
    "office.com",
    ".office.net",
    ".office365.com",
    ".officeppe.com",
    ".officeppe.net",
    ".onedrive.com",
    "onedrive.com",
    ".onenote.com",
    "onenote.com",
    ".onenote.net",
    "outlook-int.com",
    ".outlook.com",
    "003-1-d.outlook.com",
    "003-1-d.prod.outlook.com",
    "outlook.com",
    "pod71084-pri.outlook.com",
    "pod71084.outlook.com",
    ".pfx.ms",
    ".s-microsoft.com",
    ".s-msft.com",
    ".s-msn.com",
    ".sfx-df.ms",
    ".sfx-int.ms",
    ".sfx.ms",
    ".sharepoint.com",
    ".sharepointonline.com",
    ".skype.com",
    "community-stage.skype.com",
    ".skype.net",
    ".skypeassets.com",
    ".sqlazurelabs.com",
    ".surface.com",
    ".syncxp.net",
    ".trouter.io",
    ".virtualearth.net",
    ".visualstudio.com",
    "visualstudio.com",
    ".windows-int.net",
    ".windows.com",
    "insidersurveys.windows.com",
    "www.insidersurveys.windows.com",
    ".windows.net",
    ".windowsazure.com",
    ".windowsmedia.com",
    ".windowsphone-int.com",
    ".windowsphone-int.net",
    ".windowsphone.com",
    ".windowsphone.net",
    ".windowssearch.com",
    ".windowsstore.com",
    ".wlxrs.com",
    ".xbox.com",
    ".xboxlive.com",
    ".zune.net"
  ]
}

=== kroim/MISP/app/files/warninglists/lists/url-shortener/list.json
{
  "name": "List of known URL Shorteners domains",
  "version": 6,
  "description": "Event contains one or more entries of known Shorteners domains",
  "matching_attributes": [
    "domain",
    "hostname",
    "domain|ip",
    "url",
    "uri"
  ],
  "type": "hostname",
  "list": [
    "1url.com",
    "adcraft.co",
    "adcrun.ch",
    "adflav.com",
    "adf.ly",
    "aka.gr",
    "amzn.to",
    "bc.vc",
    "bee4.biz",
    "bit.do",
    "bit.ly",
    "bitly.com",
    "buff.ly",
    "buzurl.com",
    "cektkp.com",
    "cur.lv",
    "cut.by",
    "cutt.us",
    "db.tt",
    "dft.ba",
    "filoops.info",
    "fun.ly",
    "fzy.co",
    "gog.li",
    "golinks.co",
    "goo.gl",
    "hit.my",
    "hyperurl.co",
    "id.tl",
    "iplogger.com",
    "is.gd",
    "ity.im",
    "j.mp",
    "linkto.im",
    "link.zip.net",
    "lnk.co",
    "lnk.direct",
    "lnkd.in",
    "mcaf.ee",
    "nov.io",
    "ow.ly",
    "p6l.org",
    "picz.us",
    "po.st",
    "prettylinkpro.com",
    "q.gs",
    "qr.ae",
    "qr.net",
    "scrnch.me",
    "shortquik.com",
    "sk.gy",
    "smarturl.it",
    "snip.ly",
    "su.pr",
    "s.rlp.de",
    "t.co",
    "tinyarrows.com",
    "tiny.cc",
    "tinyurl.com",
    "tota2.com",
    "tr.im",
    "tweez.me",
    "twitthis.com",
    "u.bb",
    "urlz.fr",
    "u.to",
    "v.gd",
    "vzturl.com",
    "wp.me",
    "x.co",
    "xlinkz.info",
    "xtu.me",
    "yourls.org",
    "youtu.be",
    "yu2.it",
    "zpag.es",
    "iplogger.org"
  ]
}

=== kroim/MISP/app/files/warninglists/lists/rfc6598/list.json
{
  "list": [
    "100.64.0.0/10"
  ],
  "type": "cidr",
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip"
  ],
  "description": "Event contains one or more entries part of the RFC 6598 CIDR blocks - Special Use IPv4 Addresses",
  "version": 3,
  "name": "List of RFC 6598 CIDR blocks"
}

=== kroim/MISP/app/files/warninglists/lists/public-dns-v6/list.json
{
  "description": "Event contains one or more public IPv6 DNS resolvers as attribute with an IDS flag set",
  "list": [
    "2606:4700:4700::1111",
    "2606:4700:4700::1001",
    "2001:1488:800:400::130",
    "2001:14b8:100:350::2",
    "2001:14b8:100:8350::1",
    "2001:14b8:100:8350::8",
    "2001:1608:10:167:342::eb52",
    "2001:1608:10:195:3:dead:beef:cafe",
    "2001:1608:10:25::1c04:b12f",
    "2001:1608:10:25::9249:d69b",
    "2001:1620:2777:1::10",
    "2001:1620:2777:1::11",
    "2001:1620:2777::2",
    "2001:19f0:5001:133:5400:ff:fe30:d565",
    "2001:19f0:5801:11:5400:ff:fe2d:7724",
    "2001:19f0:7001:929:5400:ff:fe30:50af",
    "2001:19f0:8001:5e:5400:ff:fe35:c3ae",
    "2001:1a68::d911:2244",
    "2001:1bc0::ffff:aaaa:2",
    "2001:1bc0::ffff:bbbb:2",
    "2001:2040:39::5",
    "2001:418:3ff::1:53",
    "2001:418:3ff::53",
    "2001:41d0:52:cff::1325",
    "2001:41d0:52:f00::413",
    "2001:41d0:8:be92::1",
    "2001:41d0:a:1011::1",
    "2001:41d0:a:28::1",
    "2001:428:101:100:205:171:2:65",
    "2001:428:101:100:205:171:3:65",
    "2001:428::1",
    "2001:450:2005:1::4",
    "2001:450:2005:2::4",
    "2001:450:2005:2::5",
    "2001:450:2005:3::5",
    "2001:468:c80:2101:0:100:0:22",
    "2001:468:c80:4101:0:100:0:42",
    "2001:470:0:45::2",
    "2001:470:0:69::2",
    "2001:470:0:6e::2",
    "2001:470:0:78::2",
    "2001:470:0:7d::2",
    "2001:470:0:8c::2",
    "2001:470:0:90::2",
    "2001:470:0:9d::2",
    "2001:470:0:c0::2",
    "2001:470:1f14:fd8::2",
    "2001:470:20::2",
    "2001:470:26:1c8::1",
    "2001:470:6d:80:224:1dff:fe84:797",
    "2001:470:6d:80:a5f6:5a97:a53:71cb",
    "2001:470:6d:80:c4f1:32a:4521:c34",
    "2001:470:6d:f1e:1337:360:dead:beef",
    "2001:470:8e08::",
    "2001:470:d:bb7::8888",
    "2001:470:f032:1::254",
    "2001:4860:4860::8844",
    "2001:4860:4860::8888",
    "2001:4870:6082:3::100",
    "2001:4870:6082:3::5",
    "2001:4870:8000:3::100",
    "2001:4870:8000:3::5",
    "2001:4ce8::53",
    "2001:4dd0:fd5e::53",
    "2001:4f8:0:2::14",
    "2001:550:1:1::d",
    "2001:5b8:1::5",
    "2001:610:1108:5010::130",
    "2001:638:902:1::10",
    "2001:648:2ffc:100::211",
    "2001:678:1::206",
    "2001:67c:15e8:d1::18",
    "2001:67c:15e8:d1::19",
    "2001:67c:240c:214::4",
    "2001:67c:240c:214::5",
    "2001:67c:2b0::1",
    "2001:67c:2b0::2",
    "2001:67c:2b24:1000::10",
    "2001:67c:2b24:1000::11",
    "2001:6b0:3f::a",
    "2001:7b8:1509::1",
    "2001:840:0:200::1",
    "2001:840:200::",
    "2001:840:2010:413::100",
    "2001:910:800::12",
    "2001:910:800::40",
    "2001:978:1:1::d",
    "2001:978:1:2::d",
    "2001:b000:168::1",
    "2001:b08:2:280::4:1",
    "2001:bf0::2",
    "2001:ec0:1::1",
    "2001:ec0:3::3",
    "2400:6180:0:d0::38:d001",
    "2400:8900::f03c:91ff:fe70:c452",
    "2402:2f80:5::",
    "2402:9e80:1::1:e554",
    "2403:5680::1:200f",
    "2407:9000:0:4::2",
    "2600:3c00::20:b1ff",
    "2600:3c02::f03c:91ff:fe84:cb54",
    "2600:3c02::f03c:91ff:fee0:5e5",
    "2600::1",
    "2600::2",
    "2602:3f:e75c:1bff::1",
    "2602:ffb6:2:0:f816:3eff:fe23:ae28",
    "2602:ffc5:30::1:d69b",
    "2604:a880:1:20::c5b:1001",
    "2604:a880:400:d0::6d6:2001",
    "2605:f700:c0:1::1089:53ef",
    "2607:fa88:1::2",
    "2610:130:100:3::200",
    "2610:a1:1018::22",
    "2610:a1:1018::23",
    "2610:a1:1018::24",
    "2610:a1:1018::25",
    "2610:a1:1018::26",
    "2610:a1:1018::27",
    "2610:a1:1018::28",
    "2610:a1:1018::29",
    "2610:a1:1018::30",
    "2610:a1:1018::31",
    "2610:a1:1018::32",
    "2610:a1:1018::33",
    "2610:a1:1018::34",
    "2610:a1:1018::35",
    "2610:a1:1018::5",
    "2610:a1:1019::22",
    "2610:a1:1019::23",
    "2610:a1:1019::24",
    "2610:a1:1019::25",
    "2610:a1:1019::26",
    "2610:a1:1019::27",
    "2610:a1:1019::28",
    "2610:a1:1019::29",
    "2610:a1:1019::30",
    "2610:a1:1019::31",
    "2610:a1:1019::32",
    "2610:a1:1019::33",
    "2610:a1:1019::34",
    "2610:a1:1019::35",
    "2610:a1:1019::5",
    "2620:0:ccc::2",
    "2620:0:ccd::2",
    "2620:74:1b::1:1",
    "2620:74:1c::2:2",
    "2a00-1508-0-4--9.puntcat.ip6.guifi.net.",
    "2a00-1dc0-cafe--ad86-fa7e.static.host.",
    "2a00-1dc0-cafe--c6af-c19d.static.host.",
    "2a00:12d8:7002::2",
    "2a00:1508:0:4::9",
    "2a00:1ca8:a7::1e9",
    "2a00:1dc0:cafe::ad86:fa7e",
    "2a00:1dc0:cafe::c6af:c19d",
    "2a00:5881:8100:1000::3",
    "2a00:5884:8218::1",
    "2a00:dcc0:eda:88:245:71:858e:a15",
    "2a00:dcc0:eda:98:183:193:d85a:389b",
    "2a00:dcc7:2202:11::7b28",
    "2a00:dcc7:2202:14::2",
    "2a00:f48:100c:7b::2",
    "2a00:f48:100c:7e::2",
    "2a01:4f8:131:1278::2",
    "2a01:4f8:141:4281::3000",
    "2a01:4f8:151:90e9::2",
    "2a01:4f8:151:90e9::b",
    "2a01:4f8:161:4109::6",
    "2a01:4f8:191:306c::2",
    "2a02:2178:1:2::2",
    "2a02:2ca0:64:22::2",
    "2a02:6b8::feed:ff",
    "2a02:7aa0:1201::f60e:2719",
    "2a02:7aa0:1619::4f50:a69",
    "2a02:940:0:4293::100",
    "2a02:e00:fffd:139::9",
    "2a03:b0c0:0:1010::62:f001",
    "2a03:b0c0:3:d0::7c:5001",
    "2a04:92c7:7:7::14ae:460a",
    "2a04:9dc0:c1:7::cb9:f785",
    "2a05:b0c6:5e4::53",
    "2a05:dfc7:5::53",
    "2a05:dfc7:5::5353",
    "2c0f:fda8:5::2ed1:d2ec",
    "::ffff:9538:1aed",
    "::ffff:9e45:abfe",
    "ClemenTroniQ89-1-pt.tunnel.tserv11.ams1.ipv6.he.net.",
    "anyone.dnsrec.meo.ws.",
    "anytwo.dnsrec.meo.ws.",
    "b-root.cesidian.info.",
    "canopus.ne2000.nl.",
    "cl-849.hel-01.fi.sixxs.net.",
    "crt-public-dns-a.cesidianroot.eu.",
    "cznic-public-dns-1.nic.cz.",
    "dlfw-rdns-01.dlfw.twtelecom.net.",
    "dns.yandex.ru.",
    "dns01.jordbruksverket.se.",
    "dns02.jordbruksverket.se.",
    "dns1.host.net.",
    "dns1.lon.gblx.net.",
    "dns1.phx.gblx.net.",
    "dns1.totbb.net.",
    "dns2.phx.gblx.net.",
    "dns2.roc.gblx.net.",
    "dns2.totbb.net.",
    "dnsdist.mysrvr.net.",
    "dnsres1.nic.cz.",
    "eu-res1.dns.cogentco.com.",
    "eu-res2.dns.cogentco.com.",
    "freya.stelas.de.",
    "google-public-dns-b.google.com.",
    "hntp1.hinet.net.",
    "homens.b-hs.de.",
    "host19-65-static.59-88-b.business.telecomitalia.it.",
    "jeru.cns.ipv6.vt.edu.",
    "log.bzh.",
    "lpc1.stu.neva.ru.",
    "lucy.s.imvry.pw.",
    "mail2.cesidianroot.eu.",
    "na-res1.dns.cogentco.com.",
    "ns-3.iastate.edu.",
    "ns.ipv6.uni-leipzig.de.",
    "ns0.fdn.org.",
    "ns1.ams.dns.lchi.mp.",
    "ns1.ata.dns.lchi.mp.",
    "ns1.fdn.fr.",
    "ns1.hnd.dns.lchi.mp.",
    "ns1.init7.net.",
    "ns1.nl.dns.d0wn.biz.",
    "ns1.probe-networks.de.",
    "ns1.sea.dns.lchi.mp.",
    "ns1.sg.dns.d0wn.biz.",
    "ns1.shodan.io.",
    "ns1.syd.dns.lchi.mp.",
    "ns1.twtelecom.net.",
    "ns10.init7.net.",
    "ns11.init7.net.",
    "ns2.all.de.",
    "ns2.itandtel.at.",
    "ns2.powertech.no.",
    "ns2.probe-networks.de.",
    "ns2.shodan.io.",
    "ns2.sprintlink.net.",
    "ns2.twtelecom.net.",
    "ns532549.ip-149-56-26.net.",
    "open-root.cesidian.info.",
    "or.isc.org.",
    "ordns.he.net.",
    "plfgr.eu.org.",
    "primary.server.edv-froehlich.de.",
    "proxyvm.stejau.de.",
    "public-dns-a.primawebtools.de.",
    "recursif.arn-fai.net.",
    "resolver.qwest.net.",
    "resolver1.dns.trex.fi.",
    "resolver1.ipv6-sandbox.opendns.com.",
    "resolver2.dns.trex.fi.",
    "resolver2.ipv6-sandbox.opendns.com.",
    "rickhunter.ns.ielo.net.",
    "rns1.grnet.gr.",
    "secondary.server.edv-froehlich.de.",
    "services.donotuse.de.",
    "spcr-2.machadosbsmarketing.com.br.",
    "test.cesidian.info.",
    "tserv1.ams1.he.net.",
    "tserv1.dal1.he.net.",
    "tserv1.fmt2.he.net.",
    "tserv1.fra1.he.net.",
    "tserv1.mia1.he.net.",
    "tserv1.tor1.he.net.",
    "x.ns.gin.ntt.net.",
    "y.ns.gin.ntt.net.",
    "yardbird.cns.ipv6.vt.edu.",
    "zen.stack.nl."
  ],
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip"
  ],
  "type": "string",
  "name": "List of known IPv6 public DNS resolvers",
  "version": 20181114
}

=== kroim/MISP/app/files/warninglists/lists/whats-my-ip/list.json
{
  "name": "List of known domains to know external IP",
  "version": 5,
  "description": "Event contains one or more entries of known 'what's is my ip' domains",
  "matching_attributes": [
    "domain",
    "hostname",
    "domain|ip",
    "uri",
    "url"
  ],
  "type": "hostname",
  "list": [
    "2ip.ru",
    "2ip.tools",
    "aboutmyip.com",
    "api.ipify.org",
    "api.wipmania.com",
    "bearsmyip.com",
    "bot.whatismyipaddress.com",
    "checkip.amazonaws.com",
    "checkip.dns.he.net",
    "checkip.dyndns.com",
    "checkip.dyndns.es",
    "checkip.dyndns.org",
    "checkip.narak.com",
    "checkmyip.com",
    "check-my-ip.net",
    "cmyip.com",
    "cmyip.net",
    "crymyip.com",
    "curlmyip.com",
    "curlmyip.net",
    "dawhois.com",
    "dnswatch.info",
    "dpool.sina.com.cn",
    "findmyipaddress.com",
    "findmyip.org",
    "formyip.com",
    "freegeoip.net",
    "geoip.co.uk",
    "geoiptool.com",
    "geoip.vmn.net",
    "get-myip.com",
    "getmyip.org",
    "icanhazip.com",
    "ident.me",
    "ifcfg.me",
    "ifconfig.co",
    "ifconfig.me",
    "ilmioip.it",
    "indirizzo-ip.com",
    "inet-ip.info",
    "ip138.com",
    "ip-1.com",
    "ip2location.com",
    "ip2nation.com",
    "ip4.me",
    "ip-addr.es",
    "ip-address.cc",
    "ipaddresscheck.com",
    "ipaddress.com",
    "ipaddress.org",
    "ip-address.ru",
    "ip-adress.com",
    "ip-adress.eu",
    "ip.amulex.com",
    "ip.anysrc.net",
    "ip-api.com",
    "ip.cctv.pk",
    "ipchecker.info",
    "ip-check.info",
    "ipchicken.com",
    "ip.chinaz.com",
    "ip.cn",
    "ip-detect.net",
    "ipecho.net",
    "ipify.org",
    "ipinfodb.com",
    "ipinfo.info",
    "ipinfo.io",
    "ip-info.org",
    "ip-info.xyz",
    "ipleak.net",
    "iplocation.net",
    "iplogger.ru",
    "ipmonkey.com",
    "ip.my-proxy.com",
    "ip-ping.ru",
    "ip-score.com",
    "ip-secrets.com",
    "ip.taobao.com",
    "ip.tool.la",
    "iptrackeronline.com",
    "ip.tyk.nu",
    "ipv4bot.whatismyipaddress.com",
    "ipv6bot.whatismyipaddress.com",
    "ip.webmasterhome.cn",
    "ip-who-is.com",
    "ip-whois.net",
    "l2.io",
    "keliweb.it/mioip.php",
    "meip.eu",
    "meuip.net.br",
    "mioip.ch",
    "mioip.biz",
    "mioip.info",
    "mioip.it",
    "mioip.org",
    "mioip.win",
    "mio-ip.it",
    "mon-ip.com",
    "mycamip.com",
    "myexternalip.com",
    "myglobalip.com",
    "myipaddress.com",
    "my-ip-address.net",
    "myip.am",
    "myip.by",
    "myip.cc",
    "myip.cf",
    "myip.ch",
    "myip.cn",
    "myip.co.il",
    "myip.com.br",
    "myip.com.tw",
    "myip.com.ua",
    "myip.co.nz",
    "myip.cz",
    "myip.dk",
    "myip.dnsdynamic.org",
    "myip.dnsomatic.com",
    "myip.dramor.net",
    "myip.easylife.tw",
    "myip.es",
    "myip.eu",
    "myip.fi",
    "myip.gr",
    "myip.heltech.se",
    "myip.ht",
    "myip.info",
    "myipinfo.net",
    "myip.io",
    "myip.is",
    "myip.israel.net",
    "myip.jacware.com",
    "myip.knet.ca",
    "myip.kz",
    "myip.ma",
    "myip.ms",
    "myip.mudfish.net",
    "myip.mysau.com.au",
    "myip.net",
    "myip.nl",
    "myip.nmonitoring.com",
    "myip.northstate.net",
    "myipnow.com",
    "myip.nu",
    "myipnumber.com",
    "myiponline.com",
    "myip.ozymo.com",
    "myip.report",
    "myip.rs.sr",
    "myip.ru",
    "myip.sdu.dk",
    "myip.se",
    "myip.shorty.org",
    "myip.surfeasy.com",
    "myip.telespex.com",
    "myip.tk",
    "myip.tw",
    "myip.ua.edu",
    "myip.uconn.edu",
    "myip.v6shell.org",
    "myip.zone",
    "mylocation.org",
    "readip.info",
    "shmyip.com",
    "show-ip.com",
    "showipinfo.net",
    "showip.net",
    "showmemyip.com",
    "showmyipaddress.com",
    "showmyipaddress.eu",
    "showmyip.com",
    "showmyip.com.ar",
    "showmyip.co.uk",
    "show-my-ip.de",
    "showmyip.gr",
    "showmyipnow.com",
    "smart-ip.net",
    "tell-my-ip.com",
    "tracemyip.com",
    "tracemyip.org",
    "trackip.net",
    "ultratools.com",
    "utrace.de",
    "v4.ident.me",
    "v6.ident.me",
    "vermiip.es",
    "vinflag.com",
    "whatismybrowser.com",
    "whatismyipaddress.com",
    "whatismyip.akamai.com",
    "whatismyip.ca",
    "whatismyip.com",
    "whatismyip.com.br",
    "whatismyip.li",
    "whatismyip.net",
    "whatismyip.org",
    "whatismypublicip.com",
    "whatmyip.us",
    "whatsmyipaddress.com",
    "whatsmyipaddress.net",
    "whats-my-ip-address.org",
    "whatsmyip.ie",
    "whatsmyip.net",
    "whatsmyip.org",
    "whatsmyip.us",
    "whereisip.net",
    "whoer.net",
    "wtfismyip.com",
    "www.ip.cn",
    "xmyip.com",
    "yougetsignal.com",
    "youip.net",
    "your-ip-address.com",
    "yourip.us",
    "myip.opendns.com",
    "whatismyip.everdot.org",
    "ip-info.ff.avast.com",
    "ipapi.co"
  ]
}

=== kroim/MISP/app/files/warninglists/lists/microsoft-attack-simulator/list.json
{
  "matching_attributes": [
    "ip-src",
    "ip-dst",
    "domain|ip",
    "hostname"
  ],
  "version": 20180711,
  "list": [
    "52.168.52.134",
    "securescore-user-prod.cloudapp.net",
    "portal.docdeliveryapp.com",
    "portal.hardwarecheck.net",
    "portal.payrolltooling.com",
    "portal.docdeliveryapp.net",
    "portal.docstoreinternal.com",
    "portal.prizesforall.com",
    "portal.payrolltooling.net",
    "portal.prizegiveaway.net",
    "portal.hrsupportint.com"
  ],
  "name": "List of known Office 365 Attack Simulator used for phishing awareness campaigns",
  "description": "Office 365 URLs and IP address ranges used for their attack simulator in Office 365 Threat Intelligence",
  "type": "substring"
}
